// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Appointment struct {
	ID        int32          `json:"id"`
	Date      time.Time      `json:"date"`
	Time      time.Time      `json:"time"`
	DoctorID  int32          `json:"doctor_id"`
	UserID    int32          `json:"user_id"`
	Status    string         `json:"status"`
	Reason    sql.NullString `json:"reason"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type Doctor struct {
	ID            int32          `json:"id"`
	Name          string         `json:"name"`
	HospitalID    sql.NullInt32  `json:"hospital_id"`
	SpecialtyID   sql.NullInt32  `json:"specialty_id"`
	LicenseNumber string         `json:"license_number"`
	Phone         sql.NullString `json:"phone"`
	Password      string         `json:"password"`
	Email         string         `json:"email"`
	Status        string         `json:"status"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type Hospital struct {
	ID        int32          `json:"id"`
	Name      string         `json:"name"`
	Location  string         `json:"location"`
	Level     string         `json:"level"`
	Rating    sql.NullString `json:"rating"`
	Phone     sql.NullString `json:"phone"`
	Email     sql.NullString `json:"email"`
	Address   sql.NullString `json:"address"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type HospitalSpecialty struct {
	HospitalID  sql.NullInt32 `json:"hospital_id"`
	SpecialtyID sql.NullInt32 `json:"specialty_id"`
}

type Review struct {
	ID         int32          `json:"id"`
	HospitalID int32          `json:"hospital_id"`
	UserID     int32          `json:"user_id"`
	Rating     int32          `json:"rating"`
	Comment    sql.NullString `json:"comment"`
	CreatedAt  time.Time      `json:"created_at"`
}

type Specialty struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
}

type User struct {
	ID        int32          `json:"id"`
	Fullname  string         `json:"fullname"`
	Email     string         `json:"email"`
	Phone     sql.NullString `json:"phone"`
	Password  string         `json:"password"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}
